version: '3.7'
services:
  redis:
     image: redis:alpine
     command: redis-server --port 6379
     container_name: redisdb
     hostname: redisdb
     labels:
       - "name=redis"
       - "mode=standalone"
     ports:
       - 6379:6379
  mysql:
     image: mariadb:10
     container_name: mysqldb
     ports:
        - 3306:3306
     volumes:
        - ./mysql/conf.d:/etc/mysql/conf.d
        - ./mysql/data:/var/lib/mysql
        - ./mysql/initdb.d/create_table.sql:/docker-entrypoint-initdb.d/setup.sql
     env_file: ./mysql/.env
     environment:
        TZ: Asia/Seoul
     restart: always
  zookeeper:
     image: wurstmeister/zookeeper:3.4.6
     container_name: zookeeper
     ports:
        - 2181:2181
  kafka:
     image: wurstmeister/kafka:2.12-2.3.0
     container_name: kafka
     depends_on:
        - zookeeper
     ports:
        - 9092:9092
     environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_CREATE_TOPICS: "systems_topic:2:2"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     volumes:
        - ./kafka/docker.sock:/var/run/docker.sock
  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
     container_name: elasticsearch
     ports:
        - 9200:9200
        - 9300:9300
     configs:
        - source: elastic_config
          target: /usr/share/elasticsearch/config/elasticsearch.yml
     environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        ELASTIC_PASSWORD: password
        discovery.type: single-node
     networks:
        - elk
     deploy:
        mode: replicated
        replicas: 1
  logstash:
     image: docker.elastic.co/logstash/logstash:7.10.0
     container_name: logstash
     ports:
        - 5044:5044
        - 5000:5000
        - 9600:9600
     configs:
        - source: logstash_config
          target: /usr/share/logstash/config/logstash.yml
        - source: logstash_pipeline
          target: /usr/share/logstash/pipeline/logstash.conf
     environment:
        LS_JAVA_OPTS: "-Xms256m -Xms256m"
     networks:
        - elk
     deploy:
        mode: replicated
        replicas: 1
  kibana:
     image: docker.elastic.co/kibana/kibana:7.10.0
     container_name: kibana
     ports:
        - 5601:5601
     configs:
        - source: kibana_config
          target: /usr/share/kibana/config/kiban.yml
     networks:
        - elk
     deploy:
        mode: replicated
        replicas: 1
configs:
  elastic_config:
     file: ./elk/elasticsearch/config/elasticsearch.yml
  logstash_config:
     file: ./elk/logstash/config/logstash.yml
  logstash_pipeline:
     file: ./elk/logstash/pipeline/logstash.conf
  kibana_config:
     file: ./elk/kibana/config/kibana.yml
networks:
  elk:
     name: elk-network
     driver: bridge
